const mockClothingItems = [
  {
    id: '1',
    name: 'Classic White T-Shirt',
    brand: 'Essential Wear',
    description: 'A timeless classic white t-shirt made from premium cotton. Perfect for everyday wear with a comfortable fit and durable construction.',
    price: 29.99,
    originalPrice: 39.99,
    imageUrl: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&auto=format&fit=crop&q=60',
    images: [
      { url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab', alt: 'White t-shirt front' },
      { url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a', alt: 'White t-shirt back' },
      { url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a', alt: 'Model wearing t-shirt' },
      { url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a', alt: 'T-shirt detail' },
    ],
    sizes: [
      { value: 'xs', label: 'XS', available: true },
      { value: 's', label: 'S', available: true },
      { value: 'm', label: 'M', available: true },
      { value: 'l', label: 'L', available: false },
      { value: 'xl', label: 'XL', available: true },
    ],
    colors: [
      { name: 'White', value: '#FFFFFF', available: true },
      { name: 'Black', value: '#000000', available: true },
      { name: 'Gray', value: '#808080', available: false },
    ],
    fabric: '100% Premium Cotton',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    features: [
      'Premium cotton fabric',
      'Regular fit',
      'Crew neck',
      'Short sleeves',
      'Pre-shrunk',
    ],
    stock: 15,
    rating: 4.5,
    reviewCount: 128,
    category: 'T-Shirts',
    tags: ['casual', 'basic', 'summer']
  },
  {
    id: '2',
    name: 'Blue Denim Jeans',
    brand: 'Essential Wear',
    description: 'A timeless classic white t-shirt made from premium cotton. Perfect for everyday wear with a comfortable fit and durable construction.',
    price: 79.99,
    originalPrice: 99.99,
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop&q=60',
    images: [
      { url: 'https://images.unsplash.com/photo-1542272604-787c3835535d', alt: 'Blue denim jeans front' },
      { url: 'https://images.unsplash.com/photo-1542272604-787c3835535d', alt: 'Blue denim jeans back' },
      { url: 'https://images.unsplash.com/photo-1542272604-787c3835535d', alt: 'Model wearing jeans' },
      { url: 'https://images.unsplash.com/photo-1542272604-787c3835535d', alt: 'Jeans detail' },
    ],
    sizes: [
      { value:'s', label: 'S', available: true },
      { value:'m', label: 'M', available: true },
      { value: 'l', label: 'L', available: true },
      { value: 'xl', label: 'XL', available: false },
      { value: 'xxl', label: 'XXL', available: true },
    ],
    colors: [
      { name: 'Blue', value: '#0000FF', available: true },
      { name: 'Black', value: '#000000', available: true },
      { name: 'Gray', value: '#808080', available: false },
    ],
    fabric: '100% Leather',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    features: [
      'Premium leather fabric',
      'Regular fit',
      'Crew neck',
      'Short sleeves',
      'Pre-shrunk',
    ],
    stock: 10,
    rating: 4.7,
    reviewCount: 183,
    category: 'Pants',
    tags: ['denim', 'casual', 'everyday']
  },
  {
    id: '3',
    name: 'Black Leather Jacket',
    brand: 'Essential Wear',
    description: 'A timeless classic white t-shirt made from premium cotton. Perfect for everyday wear with a comfortable fit and durable construction.',
    price: 149.99,
    originalPrice: 199.99,
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=60',
    images: [
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5', alt: 'Black leather jacket front' },
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5', alt: 'Black leather jacket back' },
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5', alt: 'Model wearing jacket' },
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5', alt: 'Jacket detail' },
    ],
    sizes: [
      { value:'s', label: 'S', available: true },
      { value:'m', label: 'M', available: true },
      { value: 'l', label: 'L', available: true },
      { value: 'xl', label: 'XL', available: false },
      { value: 'xxl', label: 'XXL', available: true },
    ],
    colors: [
      { name: 'Black', value: '#000000', available: true },
      { name: 'Gray', value: '#808080', available: false },
    ],
    fabric: '100% Leather',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    features: [
      'Premium leather fabric',
      'Regular fit',
      'Crew neck',
      'Short sleeves',
      'Pre-shrunk',
    ],
    stock: 5,
    rating: 4.9,
    reviewCount: 150,
    category: 'Jackets',
    tags: ['leather', 'casual', 'winter']
  },
] 

export default mockClothingItems;