const mockClothingItems = [
  {
    id: '1',
    name: 'Classic White T-Shirt',
    brand: 'Essential Wear',
    description: 'A timeless classic white t-shirt made from premium cotton. Perfect for everyday wear with a comfortable fit and durable construction.',
    price: 29.99,
    originalPrice: 39.99,
    imageUrl: '/tshirt.jpg',
    images: [
      { url: '/tshirt.jpg', alt: 'White t-shirt front' },
      { url: '/tshirt-black.jpg', alt: 'Black t-shirt front' },
      { url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a', alt: 'Model wearing t-shirt' },
      { url: 'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a', alt: 'T-shirt detail' },
    ],
    sizes: [
      { value: 'xs', label: 'XS', available: true },
      { value: 's', label: 'S', available: true },
      { value: 'm', label: 'M', available: true },
      { value: 'l', label: 'L', available: false },
      { value: 'xl', label: 'XL', available: true },
    ],
    colors: [
      { name: 'White', value: '#FFFFFF', available: true },
      { name: 'Black', value: '#000000', available: true },
      { name: 'Gray', value: '#808080', available: false },
    ],
    fabric: '100% Premium Cotton',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    features: [
      'Premium cotton fabric',
      'Regular fit',
      'Crew neck',
      'Short sleeves',
      'Pre-shrunk',
    ],
    stock: 15,
    rating: 4.5,
    reviewCount: 128,
    category: 'T-Shirts',
    tags: ['casual', 'basic', 'summer']
  },
  {
    id: '2',
    name: 'Blue Denim Jeans',
    brand: 'Essential Wear',
    description: 'A timeless classic white t-shirt made from premium cotton. Perfect for everyday wear with a comfortable fit and durable construction.',
    price: 79.99,
    originalPrice: 99.99,
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800&auto=format&fit=crop&q=60',
    images: [
      { url: 'https://images.unsplash.com/photo-1542272604-787c3835535d', alt: 'Blue denim jeans front' },
      { url: 'https://images.unsplash.com/photo-1542272604-787c3835535d', alt: 'Blue denim jeans back' },
      { url: 'https://images.unsplash.com/photo-1542272604-787c3835535d', alt: 'Model wearing jeans' },
      { url: 'https://images.unsplash.com/photo-1542272604-787c3835535d', alt: 'Jeans detail' },
    ],
    sizes: [
      { value:'s', label: 'S', available: true },
      { value:'m', label: 'M', available: true },
      { value: 'l', label: 'L', available: true },
      { value: 'xl', label: 'XL', available: false },
      { value: 'xxl', label: 'XXL', available: true },
    ],
    colors: [
      { name: 'Blue', value: '#0000FF', available: true },
      { name: 'Black', value: '#000000', available: true },
      { name: 'Gray', value: '#808080', available: false },
    ],
    fabric: '100% Leather',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    features: [
      'Premium leather fabric',
      'Regular fit',
      'Crew neck',
      'Short sleeves',
      'Pre-shrunk',
    ],
    stock: 10,
    rating: 4.7,
    reviewCount: 183,
    category: 'Pants',
    tags: ['denim', 'casual', 'everyday']
  },
  {
    id: '3',
    name: 'Black Leather Jacket',
    brand: 'Essential Wear',
    description: 'A timeless classic white t-shirt made from premium cotton. Perfect for everyday wear with a comfortable fit and durable construction.',
    price: 149.99,
    originalPrice: 199.99,
    imageUrl: 'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=800&auto=format&fit=crop&q=60',
    images: [
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5', alt: 'Black leather jacket front' },
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5', alt: 'Black leather jacket back' },
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5', alt: 'Model wearing jacket' },
      { url: 'https://images.unsplash.com/photo-1551028719-00167b16eac5', alt: 'Jacket detail' },
    ],
    sizes: [
      { value:'s', label: 'S', available: true },
      { value:'m', label: 'M', available: true },
      { value: 'l', label: 'L', available: true },
      { value: 'xl', label: 'XL', available: false },
      { value: 'xxl', label: 'XXL', available: true },
    ],
    colors: [
      { name: 'Black', value: '#000000', available: true },
      { name: 'Gray', value: '#808080', available: false },
    ],
    fabric: '100% Leather',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    features: [
      'Premium leather fabric',
      'Regular fit',
      'Crew neck',
      'Short sleeves',
      'Pre-shrunk',
    ],
    stock: 5,
    rating: 4.9,
    reviewCount: 150,
    category: 'Jackets',
    tags: ['leather', 'casual', 'winter']
  },
  {
    id: '4',
    name: 'Green Sleeveless Dress',
    brand: 'Essential Wear',
    description: 'A beautiful long green dress on a hanger on a white wall',
    price: 29.99,
    originalPrice: 39.99,
    imageUrl: '/dress.jpg',
    images: [
      { url: '/dress.jpg', alt: 'Blue denim jeans front' },
      { url: '/dress.jpg', alt: 'Blue denim jeans back' },
      { url: '/dress.jpg', alt: 'Model wearing jeans' },
      { url: '/dress.jpg', alt: 'Jeans detail' },
    ],
    sizes: [
      { value:'s', label: 'S', available: true },
      { value:'m', label: 'M', available: true },
      { value: 'l', label: 'L', available: true },
      { value: 'xl', label: 'XL', available: false },
      { value: 'xxl', label: 'XXL', available: true },
    ],
    colors: [
      { name: 'Green', value: '#008000', available: true },
      { name: 'Black', value: '#000000', available: true },
      { name: 'Gray', value: '#808080', available: false },
    ],
    fabric: '100% Leather',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    features: [
      'Premium leather fabric',
      'Regular fit',
      'Crew neck',
      'Pre-shrunk',
    ],
    stock: 10,
    rating: 4.7,
    reviewCount: 183,
    category: 'Tops',
    tags: ['denim', 'casual', 'everyday']
  },
  {
    id: '5',
    name: 'Strap Top',
    brand: 'Jersey Basic',
    description: 'Jersey top with narrow shoulder straps.',
    price: 19.99,
    originalPrice: 29.99,
    imageUrl: '/data/010/0108775015.jpg',
    images: [
      { url: '/data/010/0108775015.jpg', alt: 'Black strap top front' },
      { url: '/data/010/0108775044.jpg', alt: 'White strap top front' },
      { url: '/data/010/0108775051.jpg', alt: 'Striped strap top front' },
    ],
    sizes: [
      { value: 'xs', label: 'XS', available: true },
      { value: 's', label: 'S', available: true },
      { value: 'm', label: 'M', available: true },
    ],
    colors: [
      { name: 'Black', value: '#000000', available: true },
      { name: 'White', value: '#FFFFFF', available: true },
    ],
    fabric: 'Cotton Blend',
    care: ['Machine wash cold', 'Tumble dry low', 'Do not bleach'],
    features: ['Slim fit', 'Soft cotton fabric', 'Stretchy material'],
    stock: 20,
    rating: 4.3,
    reviewCount: 54,
    category: 'Tops',
    tags: ['vest top', 'casual', 'summer']
  },
  {
    id: '6',
    name: 'Babette Leggings',
    brand: 'Jersey Fancy',
    description: 'Leggings in soft jersey with a wide panel at the waist for best fit over the tummy. The cotton content of the leggings is organic.',
    price: 24.99,
    originalPrice: 34.99,
    imageUrl: '/data/012/0120129001.jpg',
    images: [
      { url: '/data/012/0120129001.jpg', alt: 'Black leggings front' },
      { url: '/data/012/0120129014.jpg', alt: 'Grey leggings front' },
      { url: '/data/012/0120129018.jpg', alt: 'Red leggings front' },
    ],
    sizes: [
      { value: 's', label: 'S', available: true },
      { value: 'm', label: 'M', available: true },
      { value: 'l', label: 'L', available: true },
    ],
    colors: [
      { name: 'Black', value: '#000000', available: true },
      { name: 'Grey', value: '#808080', available: true },
      { name: 'Red', value: '#FF0000', available: true },
    ],
    fabric: 'Organic Cotton & Spandex',
    care: ['Machine wash cold', 'Do not tumble dry', 'Do not bleach'],
    features: ['Stretchy waistband', 'Soft jersey fabric', 'Comfort fit'],
    stock: 25,
    rating: 4.6,
    reviewCount: 85,
    category: 'Leggings',
    tags: ['leggings', 'casual', 'organic cotton']
  },
  {
    id: '7',
    name: 'Velour Pyjama',
    brand: 'Luxury Nightwear',
    description: 'Soft and luxurious velour pyjama jumpsuit, perfect for a cozy and elegant nightwear experience.',
    price: 10,
    originalPrice: 10,
    imageUrl: '/data/014/0141661022.jpg',
    images: [
      { url: '/data/014/0141661022.jpg', alt: 'White Velour pyjama front' },
      { url: '/data/014/0141661025.jpg', alt: 'Pink Velour pyjama front' },
    ],
    sizes: [
      { value: 's', label: 'S', available: true },
      { value: 'm', label: 'M', available: true },
      { value: 'l', label: 'L', available: false },
    ],
    colors: [
      { name: 'White', value: '#FFFFFF', available: true },
      { name: 'Pink', value: '#FF69B4', available: true },
    ],
    fabric: 'Application/3D',
    care: ['Hand wash only', 'Do not bleach', 'Low heat ironing'],
    features: ['Soft velour fabric', 'Elegant design', 'Full-body comfort'],
    stock: 10,
    rating: 4.7,
    reviewCount: 56,
    category: 'Nightwear',
    tags: ['luxury', 'comfortable', 'soft'],
  }
] 

export default mockClothingItems;